import simpy

class SelfDefinedException(simpy.SimPyException):
    pass